name: CI

on:
  push:
    branches: [master]
    paths-ignore: ['**.md']
  pull_request:
    branches: [master]
    paths-ignore: ['**.md']
  repository_dispatch:

jobs:
  build:
    name: Build
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "unstable"
          purs-tidy: "latest"

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Unlock tecton dependency
        run: echo $(cat packages.dhall | node -e "process.stdout.write(require('fs').readFileSync(0, 'utf-8').replace(/(https\:\/\/raw\.githubusercontent\.com\/nsaunders\/purescript\-tecton\/master\/spago\.dhall)\s+sha256\:[a-z0-9]+/m, (_, x) => x))") > packages.dhall

      - name: Install dependencies
        run: spago install

      - name: Commit packages.dhall
        uses: EndBug/add-and-commit@v9
        with:
          add: packages.dhall
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: Update tecton spago.dhall hash.

      - name: Build source
        run: spago build --no-install --purs-args '--censor-lib --strict'

      - name: Run tests
        run: spago -x test.dhall test

      - name: Check formatting
        run: purs-tidy check src

      - name: Verify Bower & Pulp
        run: |
          npm install bower pulp@16.0.0-0
          npx bower install
          npx pulp build -- --censor-lib --strict
